version: '3'
services:
  nginx:
    image: nginx:1.25.4-bookworm
    ports:
      - 8080:80
    volumes:
      - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network
  app:
    image: php:8.3-fpm-bookworm
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge